Name: Starter Workflow

on:
  push:
    branches: 
      - main
  workflow_dispatch:


jobs:
  build:
    name: Build SpringBoot Application 
    runs-on: ubuntu-latest
      steps:
        - name: install java 
          uses: actions/setup-java@v3
          with:
            distribution: 'temurin' 
            java-version: '17'

        - name: verify version 
          run: java --version 

# name: Deploying Springboot(War) to Tomcat on Azure Windows Server

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   build-springboot-app:
#     name: Build Springboot Application
#     runs-on: ubuntu-latest
#     steps:
#       - name: Install Java
#         uses: actions/setup-java@v3
#         with:
#           java-version: '17'
#           distribution: 'temurin'

#       - name: Verify Java Version
#         run: java -version


