Name: Starter Workflow

on:
  push:
    branches: 
      - main
  workflow_dispatch:


jobs:
  build:
    name: Build SpringBoot Application 
    runs-on: ubuntu-latest
      steps:
        - name: install java 
          uses: actions/setup-java@v3
          with:
            distribution: 'temurin' 
            java-version: '17'



