name: SpringBoot Application

on:
  push:
    branches:
      - main
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

